#!/bin/bash
if [ -z "${NODE_ENV}" ]; then
  export NODE_ENV=${1:-test}
fi

if [ -z "${PORT}" ]; then
  export PORT=${2:-3001}
fi

if [ -z "${SECRET_KEY}" ]; then
  export SECRET_KEY=${3:-secret}
fi

istanbul cover ./node_modules/.bin/_mocha -- --opts mocha.opts
